"""
This type stub file was generated by pyright.
"""

from ursina import *
from ursina.prefabs.primitives import *

point_shader = ...
if __name__ == '__main__':
    app = ...
    b = ...
