"""
This type stub file was generated by pyright.
"""

from ursina import *

"""
This type stub file was generated by pyright.
"""
class Circle(Mesh):
    def __init__(self, resolution=..., radius=..., mode=..., **kwargs) -> None:
        ...
    


if __name__ == '__main__':
    app = ...
    e = ...
    origin = ...
    ed = ...
