"""
This type stub file was generated by pyright.
"""

from ursina import Mesh

"""
This type stub file was generated by pyright.
"""
class Cone(Mesh):
    def __init__(self, resolution=..., radius=..., height=..., add_bottom=..., mode=..., **kwargs) -> None:
        ...



if __name__ == '__main__':
    app = ...
    e = ...
    origin = ...
    ed = ...
