"""
This type stub file was generated by pyright.
"""

from ursina import *

"""
This type stub file was generated by pyright.
"""
def Cube(bevel=..., subdivisions=..., mode=..., **kwargs):
    ...

if __name__ == '__main__':
    app = ...
    e = ...
    e = ...
    _ed = ...
