"""
This type stub file was generated by pyright.
"""

from ursina import *

"""
This type stub file was generated by pyright.
"""
class Cylinder(Pipe):
    def __init__(self, resolution=..., radius=..., start=..., height=..., direction=..., mode=..., **kwargs) -> None:
        ...
    


if __name__ == '__main__':
    app = ...
    origin = ...
    ed = ...
