"""
This type stub file was generated by pyright.
"""

from ursina import *

"""
This type stub file was generated by pyright.
"""
class Grid(Mesh):
    def __init__(self, width, height, mode=..., thickness=..., **kwargs) -> None:
        ...
    


if __name__ == '__main__':
    app = ...
