"""
This type stub file was generated by pyright.
"""

from ursina import *

"""
This type stub file was generated by pyright.
"""
class Pipe(Mesh):
    def __init__(self, base_shape=..., origin=..., path=..., thicknesses=..., color_gradient=..., look_at=..., cap_ends=..., mode=..., **kwargs) -> None:
        ...
    
    def generate(self):
        ...
    


if __name__ == '__main__':
    app = ...
    path = ...
    e = ...
    origin = ...
