"""
This type stub file was generated by pyright.
"""

from ursina import *

"""
This type stub file was generated by pyright.
"""
class Plane(Mesh):
    def __init__(self, subdivisions=..., mode=..., **kwargs) -> None:
        ...
    


if __name__ == '__main__':
    app = ...
    front = ...
    _ed = ...
