"""
This type stub file was generated by pyright.
"""

import platform
import sys
import subprocess
from typing import Literal

"""Python 3.8 compatibility and platform compatibility."""
if sys.version_info < (3, 9):
    ...
else:
    Literal = ...
def get_startupinfo() -> None:
    """Return None for startupinfo argument of ``subprocess.Popen``."""
    ...

if platform.system() == 'Windows':
    def get_startupinfo() -> subprocess.STARTUPINFO:
        """Return subprocess.STARTUPINFO instance hiding the console window."""
        ...
    
