"""
This type stub file was generated by pyright.
"""

"""Create new instance copies with cooperative ``super()`` calls."""
__all__ = ['CopyBase']
class CopyBase:
    """Create new instance copies with cooperative ``super()`` calls."""
    def copy(self): # -> Self:
        """Return a copied instance of the object.

        Returns:
            An independent copy of the current object.
        """
        ...
    


