"""
This type stub file was generated by pyright.
"""

import typing
from . import copying

"""Encoding parameter handling and default."""
__all__ = ['DEFAULT_ENCODING', 'Encoding']
DEFAULT_ENCODING = ...
class Encoding(copying.CopyBase):
    """Encoding used for input and output with ``'utf-8'`` default."""
    _encoding = ...
    def __init__(self, *, encoding: typing.Optional[str] = ..., **kwargs) -> None:
        ...
    
    @property
    def encoding(self) -> str:
        """The encoding for the saved source file."""
        ...
    
    @encoding.setter
    def encoding(self, encoding: typing.Optional[str]) -> None:
        ...
    


