"""
This type stub file was generated by pyright.
"""

from .. import copying

"""Rendering parameter handling."""
__all__ = ['ParameterBase']
class ParameterBase(copying.CopyBase):
    """Rendering parameter."""
    ...


