"""
This type stub file was generated by pyright.
"""

import typing
from . import base

"""Rendering engine parameter handling."""
__all__ = ['ENGINES', 'verify_engine', 'Engine']
ENGINES = ...
DEFAULT_ENGINE = ...
REQUIRED = ...
def verify_engine(engine: str, *, required: bool = ...) -> None:
    ...

class Engine(base.ParameterBase):
    """Rendering engine parameter with ``'dot''`` default."""
    _engine = ...
    _verify_engine = ...
    def __init__(self, *, engine: typing.Optional[str] = ..., **kwargs) -> None:
        ...

    @property
    def engine(self) -> str:
        """The layout engine used for rendering
            (``'dot'``, ``'neato'``, ...)."""
        ...

    @engine.setter
    def engine(self, engine: str) -> None:
        ...



