"""
This type stub file was generated by pyright.
"""

import typing
from . import base

"""Rendering format parameter handling."""
__all__ = ['FORMATS', 'verify_format', 'Format']
FORMATS = ...
DEFAULT_FORMAT = ...
REQUIRED = ...
def verify_format(format: str, *, required: bool = ...) -> None:
    ...

class Format(base.ParameterBase):
    """Rendering format parameter with ``'pdf'`` default."""
    _format = ...
    _verify_format = ...
    def __init__(self, *, format: typing.Optional[str] = ..., **kwargs) -> None:
        ...

    @property
    def format(self) -> str:
        """The output format used for rendering
            (``'pdf'``, ``'png'``, ...)."""
        ...

    @format.setter
    def format(self, format: str) -> None:
        ...



