"""
This type stub file was generated by pyright.
"""

import typing
from . import base

"""Rendering formatter parameter handling."""
__all__ = ['FORMATTERS', 'verify_formatter', 'Formatter']
FORMATTERS = ...
REQUIRED = ...
def verify_formatter(formatter: typing.Optional[str], *, required: bool = ...) -> None:
    ...

class Formatter(base.ParameterBase):
    """Rendering engine parameter (no default)."""
    _formatter = ...
    _verify_formatter = ...
    def __init__(self, *, formatter: typing.Optional[str] = ..., **kwargs) -> None:
        ...
    
    @property
    def formatter(self) -> typing.Optional[str]:
        """The output formatter used for rendering
            (``'cairo'``, ``'gd'``, ...)."""
        ...
    
    @formatter.setter
    def formatter(self, formatter: typing.Optional[str]) -> None:
        ...
    


