"""
This type stub file was generated by pyright.
"""

from . import engines, formats, formatters, renderers

"""Mixin classes used to inherit parameter functionality."""
__all__ = ['Parameters']
class Parameters(engines.Engine, formats.Format, renderers.Renderer, formatters.Formatter):
    """Parameters for calling ``graphviz.render()`` and ``graphviz.pipe()``."""
    ...


