"""
This type stub file was generated by pyright.
"""

import typing
from . import base

"""Rendering renderer parameter handling."""
__all__ = ['RENDERERS', 'verify_renderer', 'Renderer']
RENDERERS = ...
REQUIRED = ...
def verify_renderer(renderer: typing.Optional[str], *, required: bool = ...) -> None:
    ...

class Renderer(base.ParameterBase):
    """Rendering renderer parameter (no default)."""
    _renderer = ...
    _verify_renderer = ...
    def __init__(self, *, renderer: typing.Optional[str] = ..., **kwargs) -> None:
        ...

    @property
    def renderer(self) -> typing.Optional[str]:
        """The output renderer used for rendering
            (``'cairo'``, ``'gd'``, ...)."""
        ...

    @renderer.setter
    def renderer(self, renderer: typing.Optional[str]) -> None:
        ...



