"""
This type stub file was generated by pyright.
"""

import os
import typing

"""Check and assemble commands for running Graphviz ``dot``."""
__all__ = ['DOT_BINARY', 'command']
DOT_BINARY = ...
def command(engine: str, format_: str, *, renderer: typing.Optional[str] = ..., formatter: typing.Optional[str] = ..., neato_no_op: typing.Union[bool, int, None] = ...) -> typing.List[typing.Union[os.PathLike, str]]:
    """Return ``subprocess.Popen`` argument list for rendering.

    See also:
        Upstream documentation:
        - https://www.graphviz.org/doc/info/command.html#-K
        - https://www.graphviz.org/doc/info/command.html#-T
        - https://www.graphviz.org/doc/info/command.html#-n
    """
    ...

