"""
This type stub file was generated by pyright.
"""

import typing
from .. import _tools

"""Pipe DOT source code through ``unflatten``."""
__all__ = ['UNFLATTEN_BINARY', 'unflatten']
UNFLATTEN_BINARY = ...
@_tools.deprecate_positional_args(supported_number=1)
def unflatten(source: str, stagger: typing.Optional[int] = ..., fanout: bool = ..., chain: typing.Optional[int] = ..., encoding: str = ...) -> str:
    """Return DOT ``source`` piped through ``unflatten`` preprocessor as string.

    Args:
        source: DOT source to process
            (improve layout aspect ratio).
        stagger: Stagger the minimum length of leaf edges
            between 1 and this small integer.
        fanout: Fanout nodes with indegree = outdegree = 1
            when staggering (requires ``stagger``).
        chain: Form disconnected nodes into chains of up to this many nodes.
        encoding: Encoding to encode unflatten stdin and decode its stdout.

    Returns:
        Decoded stdout of the Graphviz unflatten command.

    Raises:
        graphviz.RequiredArgumentError: If ``fanout`` is given
            but no ``stagger``.
        graphviz.ExecutableNotFound: If the Graphviz 'unflatten' executable
            is not found.
        graphviz.CalledProcessError: If the returncode (exit status)
            of the unflattening 'unflatten' subprocess is non-zero.

    See also:
        Upstream documentation:
        https://www.graphviz.org/pdf/unflatten.1.pdf
    """
    ...

