"""
This type stub file was generated by pyright.
"""

from ursina import *

"""
This type stub file was generated by pyright.
"""
fxaa_shader = ...
if __name__ == '__main__':
    app = ...
    def input(key):
        ...

