"""
This type stub file was generated by pyright.
"""

from ursina import Entity
from ursina.entity import Entity
from ursina.scripts.property_generator import generate_properties_for_class

"""
This type stub file was generated by pyright.
"""
@generate_properties_for_class()
class Camera(Entity):
    def __init__(self) -> None:
        ...

    def set_up(self):
        ...

    def orthographic_getter(self):
        ...

    def orthographic_setter(self, value):
        ...

    def fov_getter(self):
        ...

    def fov_setter(self, value):
        ...

    def clip_plane_near_getter(self):
        ...

    def clip_plane_near_setter(self, value):
        ...

    def clip_plane_far_getter(self):
        ...

    def clip_plane_far_setter(self, value):
        ...

    def aspect_ratio_getter(self):
        ...

    def shader_setter(self, value):
        ...

    def set_shader_input(self, name, value):
        ...



instance = ...
if __name__ == '__main__':
    app = ...
    e = ...
    e = ...
    e = ...
