"""
This type stub file was generated by pyright.
"""

from panda3d.core import NodePath
from ursina import *

"""
This type stub file was generated by pyright.
"""
class Collider(NodePath):
    def __init__(self, entity, shape) -> None:
        ...

    def remove(self):
        ...

    @property
    def visible(self):
        ...

    @visible.setter
    def visible(self, value):
        ...



class BoxCollider(Collider):
    def __init__(self, entity, center=..., size=...) -> None:
        ...



class SphereCollider(Collider):
    def __init__(self, entity, center=..., radius=...) -> None:
        ...



class CapsuleCollider(Collider):
    def __init__(self, entity, center=..., height=..., radius=...) -> None:
        ...



class MeshCollider(Collider):
    def __init__(self, entity, mesh=..., center=...) -> None:
        ...

    def remove(self):
        ...



if __name__ == '__main__':
    app = ...
    e = ...
    m = ...
    e = ...
    sphere = ...
    def input(key):
        ...

