"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
def duplicate(entity, copy_children=..., *args, **kwargs):
    ...

if __name__ == '__main__':
    app = ...
    e = ...
    e2 = ...
