"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
class HitInfo:
    __slots__ = ...
    def __init__(self, **kwargs) -> None:
        ...

    def __bool__(self):
        ...



