"""
This type stub file was generated by pyright.
"""

from pathlib import Path

"""
This type stub file was generated by pyright.
"""
def ursinamesh_to_obj(mesh, name=..., out_path=..., max_decimals=..., flip_faces=...):
    ...

def ursinamesh_to_dae(mesh, name, folder: Path = ..., texture_name=...):
    ...

if __name__ == '__main__':
    app = ...
    t = ...
    m = ...
