"""
This type stub file was generated by pyright.
"""

from ursina.entity import Entity
from ursina.vec3 import Vec3
from ursina import Entity

"""
This type stub file was generated by pyright.
"""
_line_model = ...
_raycaster = ...
_ray = ...
def raycast(origin, direction: Vec3 = ..., distance=..., traverse_target: Entity = ..., ignore: list = ..., debug=..., color=...):
    ...

if __name__ == '__main__':
    app = ...
    class Player(Entity):
        def update(self):
            ...
        
    
    
    wall_left = ...
    wall_right = ...
