"""
This type stub file was generated by pyright.
"""

from ursina import *

"""
This type stub file was generated by pyright.
"""
class PlaneShape:
    def __init__(self, normal=..., offset=...) -> None:
        ...
    


class BoxShape:
    def __init__(self, center=..., size=...) -> None:
        ...
    


class SphereShape:
    def __init__(self, center=..., radius=...) -> None:
        ...
    


class CapsuleShape:
    def __init__(self, center=..., radius=..., height=..., axis=...) -> None:
        ...
    


class MeshShape:
    def __init__(self, mesh=..., center=...) -> None:
        ...
    


class PhysicsBody:
    def __init__(self, name: str, world) -> None:
        ...
    
    def __getattr__(self, attribute):
        ...
    
    def attach(self):
        ...
    
    def detach(self):
        ...
    
    def remove(self):
        ...
    
    @property
    def visible(self):
        ...
    
    @visible.setter
    def visible(self, value: bool):
        ...
    
    @property
    def position(self):
        ...
    
    @position.setter
    def position(self, value):
        ...
    
    @property
    def x(self):
        ...
    
    @x.setter
    def x(self, value):
        ...
    
    @property
    def y(self):
        ...
    
    @y.setter
    def y(self, value):
        ...
    
    @property
    def z(self):
        ...
    
    @z.setter
    def z(self, value):
        ...
    
    @property
    def rotation(self):
        ...
    
    @rotation.setter
    def rotation(self, value):
        ...
    
    @property
    def scale(self):
        ...
    
    @scale.setter
    def scale(self, value):
        ...
    


class RigidBody(PhysicsBody):
    def __init__(self, world, shape, entity=..., mass=..., kinematic=..., friction=..., mask=...) -> None:
        ...
    


if __name__ == '__main__':
    app = ...
    debugNode = ...
    debugNP = ...
    world = ...
    ground = ...
    cube = ...
    sphere = ...
    capsule = ...
    platform = ...
    platform_body = ...
    def update():
        ...
    
    def input(key):
        ...
    
