"""
This type stub file was generated by pyright.
"""

from panda3d.core import NodePath

"""
This type stub file was generated by pyright.
"""
class Scene(NodePath):
    def __init__(self) -> None:
        ...
    
    def set_up(self):
        ...
    
    def clear(self):
        ...
    
    @property
    def fog_color(self):
        ...
    
    @fog_color.setter
    def fog_color(self, value):
        ...
    
    @property
    def fog_density(self):
        ...
    
    @fog_density.setter
    def fog_density(self, value):
        ...
    
    @property
    def children(self):
        ...
    
    @children.setter
    def children(self, value):
        ...
    


instance = ...
if __name__ == '__main__':
    app = ...
    e = ...
    s = ...
    def input(key):
        ...
    
