"""
This type stub file was generated by pyright.
"""

from ursina import color
from ursina.entity import Entity

"""
This type stub file was generated by pyright.
"""
class Text(Entity):
    size = ...
    default_font = ...
    default_resolution = ...
    start_tag = ...
    end_tag = ...
    def __init__(self, text=..., start_tag=..., end_tag=..., ignore=..., **kwargs) -> None:
        ...
    
    @property
    def text(self):
        ...
    
    @text.setter
    def text(self, text):
        ...
    
    def create_text_section(self, text, tag=..., x=..., y=...):
        ...
    
    @property
    def font(self):
        ...
    
    @font.setter
    def font(self, value):
        ...
    
    @property
    def color(self):
        ...
    
    @color.setter
    def color(self, value):
        ...
    
    @property
    def line_height(self):
        ...
    
    @line_height.setter
    def line_height(self, value):
        ...
    
    @property
    def width(self):
        ...
    
    @property
    def height(self):
        ...
    
    @property
    def lines(self):
        ...
    
    @property
    def resolution(self):
        ...
    
    @resolution.setter
    def resolution(self, value):
        ...
    
    @property
    def wordwrap(self):
        ...
    
    @wordwrap.setter
    def wordwrap(self, value):
        ...
    
    @property
    def origin(self):
        ...
    
    @origin.setter
    def origin(self, value):
        ...
    
    @property
    def background(self):
        ...
    
    @background.setter
    def background(self, value):
        ...
    
    def align(self):
        ...
    
    def create_background(self, padding=..., radius=..., color=...):
        ...
    
    def appear(self, speed=...):
        ...
    
    def get_width(string, font=...):
        ...
    


if __name__ == '__main__':
    app = ...
    descr = ...
    test = ...
    def input(key):
        ...
    
