"""
This type stub file was generated by pyright.
"""

from ursina.entity import Entity
from ursina import *

"""
This type stub file was generated by pyright.
"""
class Trigger(Entity):
    def __init__(self, **kwargs) -> None:
        ...
    
    def update(self):
        ...
    


if __name__ == '__main__':
    app = ...
    player = ...
    def update():
        ...
    
    t = ...
