"""
This type stub file was generated by pyright.
"""

"""
This type stub file was generated by pyright.
"""
class Empty:
    def __init__(self, **kwargs) -> None:
        ...
    


class Default:
    ...


def invoke(function, *args, **kwargs):
    ...

def after(delay, unscaled=...):
    '''@after  decorator for calling a function after some time.

        example:
        @after(.4)
        def reset_cooldown():
            self.on_cooldown = False
            self.color = color.green
    '''
    ...

def destroy(entity, delay=...):
    ...

def chunk_list(target_list, chunk_size):
    ...

def flatten_list(target_list):
    ...

def flatten_completely(container):
    ...

def enumerate_2d(array):
    ...

def size_list():
    ...

def find_sequence(name, file_types, folders):
    ...

def import_all_classes(path=..., debug=...):
    ...

def print_on_screen(text, position=..., origin=..., scale=..., duration=...):
    ...

class LoopingList(list):
    def __getitem__(self, i):
        ...
    


class PostInitCaller(type):
    def __call__(cls, *args, **kwargs):
        ...
    


if __name__ == '__main__':
    app = ...
