"""
This type stub file was generated by pyright.
"""

from panda3d.core import Vec2 as PandaVec2

"""
This type stub file was generated by pyright.
"""
class Vec2(PandaVec2):
    def __round__(self, decimals=...):
        ...

    def __repr__(self):
        ...

    def __iadd__(self, value):
        ...

    def __add__(self, value):
        ...

    def __sub__(self, value):
        ...

    @property
    def x(self):
        ...

    @x.setter
    def x(self, value):
        ...

    @property
    def y(self):
        ...

    @y.setter
    def y(self, value):
        ...

    @property
    def X(self):
        ...

    @property
    def Y(self):
        ...

    @property
    def yx(self):
        ...

    @yx.setter
    def yx(self, value):
        ...

    def __mul__(self, value):
        ...

    __rmul__ = ...
    def __truediv__(self, value):
        ...

    def __abs__(self):
        ...



if __name__ == '__main__':
    a = ...
