"""
This type stub file was generated by pyright.
"""

from panda3d.core import Vec3 as PandaVec3

"""
This type stub file was generated by pyright.
"""
class Vec3(PandaVec3):
    def __round__(self, decimals=...):
        ...

    def __repr__(self):
        ...

    def __iadd__(self, value):
        ...

    def __add__(self, value):
        ...

    def __sub__(self, value):
        ...

    @property
    def x(self):
        ...

    @x.setter
    def x(self, value):
        ...

    @property
    def y(self):
        ...

    @y.setter
    def y(self, value):
        ...

    @property
    def z(self):
        ...

    @z.setter
    def z(self, value):
        ...

    @property
    def xy(self):
        ...

    @xy.setter
    def xy(self, value):
        ...

    @property
    def yx(self):
        ...

    @yx.setter
    def yx(self, value):
        ...

    @property
    def xz(self):
        ...

    @xz.setter
    def xz(self, value):
        ...

    @property
    def yz(self):
        ...

    @yz.setter
    def yz(self, value):
        ...

    @property
    def X(self):
        ...

    @property
    def Y(self):
        ...

    @property
    def Z(self):
        ...

    def __mul__(self, value):
        ...

    __rmul__ = ...
    def __truediv__(self, value):
        ...

    def __abs__(self):
        ...



if __name__ == '__main__':
    a = ...
    a = ...
    b = ...
