"""
This type stub file was generated by pyright.
"""

from panda3d.core import Vec4 as PandaVec4

"""
This type stub file was generated by pyright.
"""
class Vec4(PandaVec4):
    def __round__(self, decimals=...):
        ...
    
    def __repr__(self):
        ...
    
    def __iadd__(self, value):
        ...
    
    def __add__(self, value):
        ...
    
    def __mul__(self, value):
        ...
    
    __rmul__ = ...
    def __truediv__(self, value):
        ...
    
    def __abs__(self):
        ...
    


if __name__ == '__main__':
    a = ...
    a = ...
    b = ...
