"""
This type stub file was generated by pyright.
"""

from panda3d.core import WindowProperties
from ursina import color

"""
This type stub file was generated by pyright.
"""
class Window(WindowProperties):
    def ready(self, title, icon, borderless, fullscreen, size, forced_aspect_ratio, position, vsync, editor_ui_enabled, window_type, render_mode):
        ...
    
    def apply_settings(self):
        ...
    
    @property
    def left(self):
        ...
    
    @property
    def right(self):
        ...
    
    @property
    def top_left(self):
        ...
    
    @property
    def top_right(self):
        ...
    
    @property
    def bottom_left(self):
        ...
    
    @property
    def bottom_right(self):
        ...
    
    def center_on_screen(self):
        ...
    
    def make_editor_gui(self):
        ...
    
    def update_aspect_ratio(self):
        ...
    
    @property
    def position(self):
        ...
    
    @position.setter
    def position(self, value):
        ...
    
    @property
    def size(self):
        ...
    
    @size.setter
    def size(self, value):
        ...
    
    @property
    def aspect_ratio(self):
        ...
    
    @property
    def forced_aspect_ratio(self):
        ...
    
    @forced_aspect_ratio.setter
    def forced_aspect_ratio(self, value):
        ...
    
    @property
    def render_mode(self):
        ...
    
    @render_mode.setter
    def render_mode(self, value):
        ...
    
    def next_render_mode(self):
        ...
    
    @property
    def title(self):
        ...
    
    @title.setter
    def title(self, value):
        ...
    
    @property
    def icon(self):
        ...
    
    @icon.setter
    def icon(self, value):
        ...
    
    @property
    def borderless(self):
        ...
    
    @borderless.setter
    def borderless(self, value):
        ...
    
    @property
    def fullscreen(self):
        ...
    
    @fullscreen.setter
    def fullscreen(self, value):
        ...
    
    @property
    def color(self):
        ...
    
    @color.setter
    def color(self, value):
        ...
    
    @property
    def vsync(self):
        ...
    
    @vsync.setter
    def vsync(self, value):
        ...
    


instance = ...
if __name__ == '__main__':
    app = ...
    button_list = ...
    startup_value = ...
    position_text = ...
    def input(key):
        ...
    
