"""
This type stub file was generated by pyright.
"""

from ursina import *

def get_world_normals(model): # -> list[Vec3]:
    ...

def colorize(model, left=..., right=..., down=..., up=..., back=..., forward=..., smooth=..., world_space=..., strength=...): # -> None:
    ...

if __name__ == '__main__':
    app = ...
