"""
This type stub file was generated by pyright.
"""

class deprecated:
    def __init__(self, message: str, /, *, category: type[Warning] | None = ..., stacklevel: int = ...) -> None:
        ...

    def __call__(self, arg, /): # -> type | _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any]:
        ...



_DEPRECATED_MSG = ...
