"""
This type stub file was generated by pyright.
"""

def normalize_v3(arr):
    ''' Normalize a numpy array of 3 component vectors shape=(n,3) '''
    ...

def generate_normals(vertices, triangles=..., smooth=...): # -> NDArray[Any]:
    ...

if __name__ == '__main__':
    vertices = ...
    t = ...
    norms = generate_normals(vertices, smooth=True)
