"""
This type stub file was generated by pyright.
"""

from ursina import *

def project_uvs(model, aspect_ratio=..., direction=..., regenerate=...): # -> None:
    ...

if __name__ == '__main__':
    app = ...
    e = ...
