"""
This type stub file was generated by pyright.
"""

from ursina import *

"""
This type stub file was generated by pyright.
"""
class Scrollable:
    def __init__(self, **kwargs) -> None:
        ...

    def update(self):
        ...

    def input(self, key):
        ...



if __name__ == '__main__':
    app = ...
    p = ...
