"""
This type stub file was generated by pyright.
"""

from ursina import Ursina

"""
This type stub file was generated by pyright.
"""
def singleton(cls, **kwargs):
    ...

if __name__ == '__main__':
    class Game(Ursina):
        ...


