"""
This type stub file was generated by pyright.
"""

from ursina import *

"""
This type stub file was generated by pyright.
"""
class SmoothFollow:
    def __init__(self, target=..., offset=..., speed=..., rotation_speed=..., rotation_offset=...) -> None:
        ...

    def update(self):
        ...



if __name__ == '__main__':
    app = ...
    player = ...
    def update():
        ...

    e = ...
    sf = ...
    def input(key):
        ...

