"""
This type stub file was generated by pyright.
"""

from ursina import *

"""
This type stub file was generated by pyright.
"""
class Animator:
    def __init__(self, animations=..., start_state=..., pause_disabled=...) -> None:
        ...

    @property
    def state(self):
        ...

    @state.setter
    def state(self, value):
        ...



if __name__ == '__main__':
    app = ...
    anim = ...
    a = ...
    def input(key):
        ...

