"""
This type stub file was generated by pyright.
"""

from ursina import Entity

"""
This type stub file was generated by pyright.
"""
class ButtonList(Entity):
    def __init__(self, button_dict, button_height=..., width=..., popup=..., color=..., highlight_color=..., selected_color=..., font=..., clear_selected_on_enable=..., **kwargs) -> None:
        ...

    @property
    def button_dict(self):
        ...

    @button_dict.setter
    def button_dict(self, value):
        ...

    def input(self, key):
        ...

    def update(self):
        ...

    def on_disable(self):
        ...

    def on_enable(self):
        ...

    @property
    def selected(self):
        ...

    @selected.setter
    def selected(self, value):
        ...



if __name__ == '__main__':
    app = ...
    default = ...
    def test(a=..., b=...):
        ...

    button_dict = ...
    bl = ...
    def input(key):
        ...

