"""
This type stub file was generated by pyright.
"""

from ursina import Button

"""
This type stub file was generated by pyright.
"""
class CheckBox(Button):
    def __init__(self, start_value=..., **kwargs) -> None:
        ...
    
    def on_click(self):
        ...
    
    @property
    def value(self):
        ...
    
    @value.setter
    def value(self, new_value):
        ...
    


if __name__ == '__main__':
    app = ...
