"""
This type stub file was generated by pyright.
"""

from ursina import Entity

"""
This type stub file was generated by pyright.
"""
class Cursor(Entity):
    def __init__(self, **kwargs) -> None:
        ...
    
    def update(self):
        ...
    


if __name__ == '__main__':
    app = ...
    cursor = ...
