"""
This type stub file was generated by pyright.
"""

from ursina import *

"""
This type stub file was generated by pyright.
"""
class Draggable(Button):
    _z_plane = ...
    def __init__(self, **kwargs) -> None:
        ...

    def input(self, key):
        ...

    def start_dragging(self):
        ...

    def stop_dragging(self):
        ...

    def update(self):
        ...

    @property
    def step(self):
        ...

    @step.setter
    def step(self, value):
        ...



if __name__ == '__main__':
    app = ...
    draggable_button = ...
    world_space_draggable = ...
