"""
This type stub file was generated by pyright.
"""

from ursina import *

"""
This type stub file was generated by pyright.
"""
class ContentTypes:
    int = ...
    float = ...
    int_math = ...
    math = ...


class InputField(Button):
    def __init__(self, default_value=..., label=..., max_lines=..., character_limit=..., text=..., active=..., **kwargs) -> None:
        ...

    def input(self, key):
        ...

    @property
    def text(self):
        ...

    @text.setter
    def text(self, value):
        ...

    @property
    def text_color(self):
        ...

    @text_color.setter
    def text_color(self, value):
        ...

    @property
    def active(self):
        ...

    @active.setter
    def active(self, value):
        ...



if __name__ == '__main__':
    app = ...
    gradient = ...
    username_field = ...
    password_field = ...
    def submit():
        ...

