"""
This type stub file was generated by pyright.
"""

from ursina import *

"""
This type stub file was generated by pyright.
"""
class Panel(Entity):
    def __init__(self, **kwargs) -> None:
        ...
    


if __name__ == '__main__':
    app = ...
    p = ...
