"""
This type stub file was generated by pyright.
"""

from ursina import *
from primitives import *

"""
This type stub file was generated by pyright.
"""
model_names = ...
if __name__ == '__main__':
    app = ...
