"""
This type stub file was generated by pyright.
"""

from ursina import *

"""
This type stub file was generated by pyright.
"""
class Sky(Entity):
    instances = ...
    def __init__(self, **kwargs) -> None:
        ...

    def update(self):
        ...



if __name__ == '__main__':
    app = ...
    def input(key):
        ...

