"""
This type stub file was generated by pyright.
"""

from ursina import *

"""
This type stub file was generated by pyright.
"""
class Slider(Entity):
    def __init__(self, min=..., max=..., default=..., height=..., text=..., dynamic=..., radius=..., bar_color=..., **kwargs) -> None:
        ...

    @property
    def value(self):
        ...

    @value.setter
    def value(self, value):
        ...

    @property
    def step(self):
        ...

    @step.setter
    def step(self, value):
        ...

    def update(self):
        ...

    def slide(self):
        ...

    def __setattr__(self, name, value):
        ...



class ThinSlider(Slider):
    def __init__(self, *args, **kwargs) -> None:
        ...



if __name__ == '__main__':
    app = ...
    box = ...
    def scale_box():
        ...

    slider = ...
    thin_slider = ...
