"""
This type stub file was generated by pyright.
"""

from ursina import *

"""
This type stub file was generated by pyright.
"""
class Sprite(Entity):
    ppu = ...
    def __init__(self, texture=..., **kwargs) -> None:
        ...
    


if __name__ == '__main__':
    app = ...
    s = ...
