"""
This type stub file was generated by pyright.
"""

from ursina import *

"""
This type stub file was generated by pyright.
"""
class Tooltip(Text):
    def __init__(self, text=..., wordwrap=..., background_color=..., **kwargs) -> None:
        ...

    def update(self):
        ...



if __name__ == '__main__':
    app = ...
    tooltip_test = ...
