"""
This type stub file was generated by pyright.
"""

from ursina import Draggable

"""
This type stub file was generated by pyright.
"""
class Space:
    def __init__(self, height=...) -> None:
        ...
    


class WindowPanel(Draggable):
    def __init__(self, title=..., content=..., **kwargs) -> None:
        ...
    
    def layout(self):
        ...
    


if __name__ == '__main__':
    app = ...
    wp = ...
    def input(key):
        ...
    
